freemex/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from registration.forms import RegistrationFormUniqueEmail
# Uncomment the next two lines to enable the admin: 
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'freemex.views.home', name='home'),
    # url(r'^freemex/', include('freemex.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	url(r'^admin/', include(admin.site.urls)),
	url(r'^test/','login.views.main'),
	url(r'^mailtest/$','login.views.mailtest'),
#	url(r'^checklogin/$','login.views.logincheck'),
	url(r'^bid/$','transaction.views.bidcheck'),
	url(r'^sell/$','transaction.views.offercheck'),
	url(r'^portfolio/$','login.views.portfolio'),
	url(r'^marketwatch/$','login.views.marketwatch'),
	url(r'^history/$','login.views.history'),
	url(r'^leaderboard/$','login.views.leader'),
	url(r'^offermodify/$','transaction.views.offermodify'),
	url(r'^bidmodify/$','transaction.views.bidmodify'),
	url(r'^deletebid/$','transaction.views.deletebid'),
	url(r'^deleteoffer/$','transaction.views.deleteoffer'),
	url(r'^analysis/$','login.views.analysis'),
#	url(r'^logout/$','login.views.logout'),
	url(r'^$','login.views.main'),
	url(r'^marquee/$','login.views.marqueecontent'),
	url(r'^notification/$','login.views.notify'),
	url(r'^faq/$','login.views.faq'),
	url(r'^accounts/register/$', 'registration.views.register',{'form_class': RegistrationFormUniqueEmail,
     'backend': 'registration.backends.default.DefaultBackend'}, name='registration_register'),
	url(r'^accounts/', include('registration.backends.default.urls')),
	url(r'^eod/$','login.views.eod'),
	url(r'^eodpage/$','login.views.eodpage'),
#	url(r'^','login.views.main'),
	
)



urlpatterns += staticfiles_urlpatterns()

login/models.py
from django.db import models
from stock.models import share
from django.contrib.auth.models import User

class login(models.Model):
	user = models.ForeignKey(User)
	email = models.EmailField(blank=True)
	password = models.CharField(max_length=250,blank=True)
	money = models.FloatField()
	
	def __unicode__(self):
		return str(self.id)
	
class user_share(models.Model):
	user = models.ForeignKey(login)
	share = models.ForeignKey(share)
	quantity = models.IntegerField()
	


class notification(models.Model):
	user = models.ForeignKey(login)
	notification = models.TextField()
	time = models.DateTimeField(auto_now=True)
	

login/views.py
from django.shortcuts import render_to_response
from login.models import login,user_share,notification
from stock.models import share
from freemex import settings
from django.template import RequestContext
from django.http import HttpResponse,HttpResponseRedirect
from transaction.models import transactions,bid,offer
from django.db.models import Q
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.core.mail import EmailMultiAlternatives
#from transaction.views import chectransaction
import decimal,random
from django import forms
from django.db import connection

def eod(request):
	if request.method == 'POST':
		if request.POST['password'] == "bowchikawowwow":
			shares = share.objects.all()
			dummy = login.objects.get(email='dummy@dummy.com')
				
			cursor = connection.cursor()
			cursor.execute("TRUNCATE TABLE `transaction_bid`")
			cursor.execute("TRUNCATE TABLE `transaction_offer`")
			
			for shareId in shares:
					try:
						current_price = round(((transactions.objects.filter(share=shareId).order_by('-id'))[0]).price,2)
					except:
						current_price = shareId.day_value
					shareId.day_value = current_price
					shareId.save()
					
					
					start = shareId.day_value
					stopbid = shareId.day_value - shareId.day_value * 0.01
					stopoffer = shareId.day_value + shareId.day_value * 0.01
					step = 0.001
					f = .001
					
					dummyquantity = round(40000/current_price)
					
					for i in range(3):
						b = bid(bidder=dummy, share=shareId, quantity=dummyquantity, quote=round((random.randrange(round(stopbid/f),round(start/f),round(step/f))*f),2))
						s = offer(seller=dummy, share=shareId, quantity=dummyquantity, quote=round((random.randrange(round(start/f),round(stopoffer/f),round(step/f))*f),2))
						b.save()
						s.save()
			return HttpResponseRedirect(request.META['HTTP_REFERER'])
		else:
			return HttpResponseRedirect(request.META['HTTP_REFERER'])
	else:
		return HttpResponseRedirect(request.META['HTTP_REFERER'])
			
def eodpage(request):
	return render_to_response('eod.html', {} , context_instance=RequestContext(request))
	
def mailtest(request):
			email_body = 'bal'
			email_subject = 'Congratulations! Your password has been successfully changed'
			email_from = 'cricketkeeda@sportskeeda.com'
			email_to = 'svksaha91@gmail.com'
			email_bcc = 'saurav.singhi@gmail.com'
			email = EmailMultiAlternatives(subject=email_subject, body=email_body, from_email=email_from, to=[email_to], bcc=[email_bcc])
			email.attach_alternative(email_body, "text/html")
			email.send()
			return HttpResponse('baal')
 
def faq(request):
	return render_to_response('faq.html', {} , context_instance=RequestContext(request))

def logout(request):
	del request.session['login_id']
	return HttpResponseRedirect(request.META['HTTP_REFERER'])
		
def buyShareList():
	shares = share.objects.all()
	sharelist = []
	for i in shares:
		sharelist.append((i.id,i.name))		
	return sharelist

def sellShareList(request):
	login_id = login.objects.get(pk=request.session['login_id'])
	shares=[]
	shares.extend(user_share.objects.filter(user=login_id))
	sharelist = []
	for i in shares:
		if i.quantity == 0:
			continue
		details = {}
		
		stock = share.objects.get(pk=i.share_id)
		details['shareid']=stock.id
		details['name']=stock.name
		details['quantity']=i.quantity
		details['min'] = round(stock.day_value*0.9,2)
		details['max'] = round(stock.day_value*1.1,2)
		sharelist.append((details))
		
	
	return sharelist

class BidForm(forms.Form):
	quantity = forms.IntegerField()
	price = forms.DecimalField(decimal_places=2,max_digits=15)
	share = forms.ChoiceField(choices=buyShareList())

def marketWatch():
	shares = share.objects.all()
	sharelist=[]

	for s in shares:
			details={}
			details['shareid'] = int(s.id)
			details['name'] = s.name
			details['starting_price'] = s.day_value
			details['min'] = round(details['starting_price']*0.9,2)
			details['max'] = round(details['starting_price']*1.1,2)
			try:
				details['current_price'] = round(((transactions.objects.filter(share=s).order_by('-id'))[0]).price,2)
				details['percentage']=((details['current_price']-details['starting_price'])/details['starting_price'])*100
			except:
				details['current_price'] = details['starting_price']
				details['percentage'] = 0
			sharelist.append(details)


	return sharelist
	
def pendingBid(request):
	bidlist=[]
	try:
		bidOrders=bid.objects.filter(bidder_id=request.session['login_id'])	
			

		for s in bidOrders:
				details={}
				details['transaction_id'] = s.id
				details['share_id'] = s.share_id
				details['share_name'] = (share.objects.get(pk=s.share_id)).name
				starting_price = (share.objects.get(pk=s.share_id)).day_value
				details['min'] = round(starting_price*0.9,2)
				details['max'] = round(starting_price*1.1,2)
				details['price'] = s.quote
				details['quantity'] = s.quantity
				bidlist.append(details)
	except:
		pass

	return bidlist
	
def pendingOffer(request):	
	offerlist=[]
	
	try:
		offerOrders=offer.objects.filter(seller_id=request.session['login_id'])	
		for s in offerOrders:
			details={}
			details['transaction_id'] = s.id
			details['share_id'] = s.share_id
			details['share_name'] = (share.objects.get(pk=s.share_id)).name
			usershare = user_share.objects.get(user=request.session['login_id'],share=s.share)
			details['max_share'] = usershare.quantity
			starting_price = (share.objects.get(pk=s.share_id)).day_value
			details['min'] = round(starting_price*0.9,2)
			details['max'] = round(starting_price*1.1,2)
			details['price'] = s.quote
			details['quantity'] = s.quantity
			offerlist.append(details)
	except:
		pass

	return offerlist	

def currentHolding(request):
	sharelist=[]
	try:
		userShares = user_share.objects.filter(user_id=request.session['login_id'])
	
	
		for s in userShares:
			if s.quantity ==0:
				continue
			details={}
			details['share_id']=s.share_id
			details['share_name']=(share.objects.get(pk=s.share_id)).name
			details['quantity']=s.quantity
			try:
				details['current_price'] = round(((transactions.objects.filter(share=s.share).order_by('-id'))[0]).price,2)
				sharesBought = transactions.objects.filter(share=s.share,buyer_id=request.session['login_id'])
				totalShare=0
				totalMoney=0
				for i in sharesBought:
					totalShare += i.quantity
					totalMoney += i.price*i.quantity
				details['buying_price']=totalMoney/totalShare
				details['profit']=(details['current_price']-details['buying_price'])*details['quantity']
			except:
				details['current_price']=share.objects.get(pk=s.share_id).day_value
				details['buying_price']=share.objects.get(pk=s.share_id).face_value
				details['profit']=(details['current_price']-details['buying_price'])*details['quantity']
				
			sharelist.append(details)
	except:
		pass
	return sharelist

def transactionhistory(request):
	transactionlist=[]
	try:
		userTransactions = transactions.objects.filter(Q(buyer_id=request.session['login_id']) | Q(seller_id=request.session['login_id'])).order_by('-id')[0:15]
		for ut in userTransactions:
			if ut.buyer_id == ut.seller_id:
				continue
			details={}
			details['share_name']=(share.objects.get(pk=ut.share_id)).name
			details['quantity']=ut.quantity
			details['price']=ut.price
			if ut.buyer_id == request.session['login_id']:
				details['type'] = "bought"
			else:
				details['type'] = "sold"
			transactionlist.append(details)
	except:
		pass
	return transactionlist

def marqueecontent(baal):
	shares = share.objects.all()
	sharelist=[]

	for s in shares:
			details={}
			details['shareid'] = int(s.id)
			details['name'] = s.name
			details['starting_price'] = s.day_value
			try:
				details['current_price'] = round(((transactions.objects.filter(share=s).order_by('-id'))[0]).price,2)
				details['difference']=((details['current_price']-details['starting_price']))
			except:
				details['current_price'] = details['starting_price']
				details['difference'] = 0
			sharelist.append(details)
	content = ''' '''
	for s in sharelist:
		content = content + '''<span class="stockbox"><a href="/analysis?q=''' + str(s['shareid']) + '''">''' + str(s['name']) + '''</a>&nbsp;''' + '''&nbsp;<span style="color: #'''
		if s['difference']>0:
			content += '''009900;">'''+str(s['current_price'])+'''&nbsp;&uarr;&nbsp'''+str(s['difference'])+'''</span></span>'''
		elif s['difference']<0:
			content += '''ff0000;">''' +str(s['current_price'])+'''&nbsp;&darr;&nbsp'''+str(s['difference'])+'''</span></span>'''
		else:
			content +='''ffff00;">'''+ str(s['current_price'])+'''&nbsp;-&nbsp'''+str(s['difference'])+'''</span></span>'''
	
	return HttpResponse(content)
		
		
def leaderboard():
	users = login.objects.all()
	dummy = login.objects.get(email='dummy@dummy.com')

	leaderList = []
	for i in users:
		if i==dummy:
			continue
		details={}
		details['email']=User.objects.get(pk=i.user_id).username
		userShares = user_share.objects.filter(user_id=i.id)
		totalValue = 0
		for userShare in userShares:
			try:
				price = ((transactions.objects.filter(share=userShare.share).order_by('-id'))[0]).price
			except:
				continue
			shareValue = userShare.quantity*price
			totalValue = totalValue + shareValue
		details['assets']= i.money + totalValue
		leaderList.append(details)
	leaderList = sorted(leaderList, key=lambda k: int(k['assets'])) 
	leaderList.reverse()
	return leaderList
		
def pricevariations():
	shares=share.objects.all()
	finalList = {}
	for shareId in shares:
		shareTransactions = transactions.objects.filter(share=shareId)
		
		list=[]
		for st in shareTransactions:
			details={}
			timeTuple = (st.time).timetuple()

templates/analysis.html
{% extends "base.html" %}


{%block content%}
<div id="holder" style="width:100%; height:400px;"></div>


 <script type="text/javascript">
 var chartData= [

{% for i in list %}

       
        
		
			
			
			{date: new Date{{i.date}}, val:{{i.val}}},
			
			
		
      
  {% endfor %}     
];

</script>


         <script type="text/javascript">
        
            
            window.onload = function(){
                var chart = new AmCharts.AmStockChart();
                chart.pathToImages = "amcharts/javascript/images/";
				chart.color = "#ffffff";
                
                var dataSet = new AmCharts.DataSet();
                dataSet.dataProvider = chartData;
                dataSet.fieldMappings = [{fromField:"val", toField:"value"}];   
                dataSet.categoryField = "date";          
                chart.dataSets = [dataSet];
                
                var stockPanel = new AmCharts.StockPanel();
                chart.panels = [stockPanel];
                
                var legend = new AmCharts.StockLegend();
                stockPanel.stockLegend = legend;                
                
                var panelsSettings = new AmCharts.PanelsSettings();
                panelsSettings.startDuration = 1;
                chart.panelsSettings = panelsSettings;   
                
                var graph = new AmCharts.StockGraph();
                graph.valueField = "value";
                graph.lineThickness = 3;
				graph.lineColor = '#ffffff';
                graph.title = "{{name}} Analysis";
                graph.fillAlphas = .2;
                stockPanel.addStockGraph(graph);

                
               var categoryAxesSettings = new AmCharts.CategoryAxesSettings();
			   categoryAxesSettings.minPeriod = "mm";
				chart.categoryAxesSettings = categoryAxesSettings;
                
                var valueAxesSettings = new AmCharts.ValueAxesSettings();
                valueAxesSettings .dashLength = 5;
                chart.valueAxesSettings  = valueAxesSettings;
                
                var chartScrollbarSettings = new AmCharts.ChartScrollbarSettings();
                chartScrollbarSettings.graph = graph;
                chartScrollbarSettings.graphType = "line";
                chart.chartScrollbarSettings = chartScrollbarSettings;
                
                var chartCursorSettings = new AmCharts.ChartCursorSettings();
                chartCursorSettings.valueBalloonsEnabled = true;
                chart.chartCursorSettings = chartCursorSettings;
                
                var periodSelector = new AmCharts.PeriodSelector();
               periodSelector.periods = [{period:"DD", count:1, label:"1 day"},
                                          {period:"DD", selected:true, count:5, label:"5 days"}
                                         ];   
                                                      
                chart.periodSelector = periodSelector;
                
                chart.write("holder");
            } 
        </script>  
  
 {% endblock %}
 
 
 
 	{%block mjs%}
	addLoadEvent(startmarquee);
  
  {% endblock %}

templates/base.html
<html>
<head>
    <title>Freemex</title>
	
{%block head%}
<script src="/static/js/jquery.min.js"></script>
<script src="/static/js/amcharts/amstock.js"></script>
<link href="/static/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="/static/css/font-awesome.min.css">
<link href="/static/css/style.css" rel="stylesheet" type="text/css" />
<link href="/static/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
<link href="/static/js/amcharts/style.css" rel="stylesheet" type="text/css" />
<script src="/static/js/bootstrap.js"></script>


{%endblock%}	



</head>

  <div class="container">
  <div class="span9 pull-right">
 <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="/">Freemex</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              
              <li class="">
                <a href="/marketwatch/">Marketwatch</a>
              </li>
			  {% if request.session.login_id %}
			  <li class="">
                <a href="/portfolio/">Portfolio</a>
              </li>
              <li class="">
                <a href="/history/">Transaction History</a>
              </li>

              <li >
                <a href="/leaderboard/">LeaderBoard</a>
              </li>
                			                 <li class="">
                <a href="/faq/">FAQ</a>
              </li>
          
			<li class="pull-right" id="profile">
			
             <a> Hi there, <strong>{{request.user.username}}</strong> </a>
           
           </li>
		   <li>
			<a href="/accounts/logout/">Logout</a>
			</li>
			<li class="notifications dropdown"> 
  <a class="dropdown-toggle inverted " id="dLabel" role="button"  data-toggle="dropdown" href="#" data-target="#"><i class="icon-bell"></i>Notification</a>
  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
  </ul>
</li>
		   
  {% else %}
  			                 <li class="">
                <a href="/faq/">FAQ</a>
              </li>
          
  <li ><a href="/accounts/login">Login</a></li>
  <li ><a href="/accounts/register">Register</a></li>
		   

	{% endif %}

            </ul>
          </div>
        </div>
      </div>
    </div>

   </div>
  </div>
  <div id="wrap">
  <div class="container main" style="margin-top:5%">
   <div class="row-fluid">
   
  <div id="marqueeborder" style= "margin-top:10px"onmouseover="pxptick=0" onmouseout="pxptick=scrollspeed">
<div id="marqueecontent">



</div>
</div>

	

	
  {%block content%}
  
  
  {% endblock %}

</div>
</div>
</div>
  {%block js%}



{% endblock %}

   <div style="height: 50px; width: 100%"> </div>
   <footer class="footer">
      <div class="container">
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>Designed and built by Team GNU/Linux Users' Group</p>
        </div>
   </footer>
 
  
  
<style type="text/css">
#marqueeborder {
	color: #cccccc;
	background-color: #000000;
	position:relative;
	height:25px; 
	overflow:hidden;
	font-size: 1em;
}
#marqueecontent {
	position:absolute;
	left:0px;
	line-height:20px;
	white-space:nowrap;
}
.stockbox {
	margin:0 10px;
}
.stockbox a {
	color: #cccccc;
}
</style>

<script type="text/javascript">

	// Original script by Walter Heitman Jr, first published on http://techblog.shanock.com

	// Set an initial scroll speed. This equates to the number of pixels shifted per tick
	var scrollspeed=2;
	var pxptick=scrollspeed;

	function startmarquee(){
		// Make a shortcut referencing our div with the content we want to scroll
		marqueediv=document.getElementById("marqueecontent");
		// Get the total width of our available scroll area
		marqueewidth=document.getElementById("marqueeborder").offsetWidth;
		// Get the width of the content we want to scroll
		contentwidth=marqueediv.offsetWidth;
		// Start the ticker at 50 milliseconds per tick, adjust this to suit your preferences
		// Be warned, setting this lower has heavy impact on client-side CPU usage. Be gentle.

		lefttime=setInterval("scrollmarquee()",50);
	}

	function scrollmarquee(){
		// Check position of the div, then shift it left by the set amount of pixels.
		temp=(2450*(-1))
		if (parseInt(marqueediv.style.left)>temp)
			marqueediv.style.left=parseInt(marqueediv.style.left)-pxptick+"px";
		// If it's at the end, move it back to the right.
		else
			marqueediv.style.left=parseInt(marqueewidth)+"px";
	}

	
	{%block mjs%}
	window.onload=startmarquee;
  
  {% endblock %}
  

  $.ajax({
        url:"/marquee/",
        success:function(result){
            $("#marqueecontent").html(result);
           
        }
		});



	
var result = "";

$.ajax({
  url: '/notification/',
  success:function(data){
	if(data!=result){
    $('.dropdown-menu').html(data);
	$('i').attr('class', 'icon-bell-alt');
	$('i').attr('style', 'color:#00ffff');
	result=data;
	}
  }
});

setInterval(function() {

$.ajax({
  url: '/notification/',
  success:function(data){
	if(data!=result){
    $('.dropdown-menu').html(data);
	$('i').attr('class', 'icon-bell-alt');
	$('i').attr('style', 'color:#00ffff');
	result=data;
	}
  }
});

$.ajax({
	url:"/marquee/",
	success:function(result){
		$("#marqueecontent").html(result);
	   
	}
	});

}, 40000);

$(".dropdown").click(function() {
	$('i').attr('class', 'icon-bell');
	$('i').removeAttr('style') 
});
</script>
  
 <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37988275-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script> 

templates/eod.html
{% extends "base.html" %}



{% block content%}


<div class=" well pagination-centered lead">

<form action='/eod/' method='POST'>
{% csrf_token %}
<input type='password' name='password'></input>
<input type='submit'>Do not press</input>
</form>


</div>


{%endblock%}

templates/history.html
{% extends "base.html" %}

{%block content%}
<h2>Market Watch</h2>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>#</th>
            <th>Share Name</th>
            <th>Opening price</th>
			<th>Current Market Price</th>
            <th>Percentage Change</th>
        </tr>
    </thead>
	
    <tbody>	
{% for share in market %}
	<tr>
		<td>{{forloop.counter}}</td>
		<td>{{share.name}}</td>
		<td>{{share.starting_price}}</td>
		<td>{{share.current_price}}</td>
		<td><a href="#{{share.share_id}}Modal" role="button" class="btn" data-toggle="modal">Launch demo modal</a></td>
	</tr>
{% endfor %}
</table>

{%endblock%}

templates/home.html
{% extends "base.html" %}



{% block content%}


<div class=" well pagination-centered lead">

<p> <strong>Market closed for today. </strong></p>
<p> Those who have not yet registered themeselves, please register now. In case you do not get your registration email, mail us at freemex@mkti.in </p>



</div>


{%endblock%}

templates/leaderboard.html
{% extends "base.html" %}

{%block content%}
<h2>LeaderBoard</h2>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>#</th>
            <th>Username</th>
            <th>Total Value</th>
        </tr>
    </thead>
	
    <tbody>	
{% for user in leaderboard %}
	<tr>
		<td>{{forloop.counter}}</td>
		<td>{{user.email}}</td>
		<td>{{user.assets}}</td>

	
	</tr>
{% endfor %}
</table>









{%endblock%}

templates/login.html
<html>
<head>
    <title>login</title>
	
{%block head%}
<script src="{{temp}}js/jquery.min.js"></script>
<link href="{{temp}}css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="{{temp}}css/bootstrap-responsive.css" rel="stylesheet" type="text/css" />
<script src="{{temp}}js/bootstrap.js"></script>

{%endblock%}	

</head>
<body>
    <h1>login</h1>


  {% if request.session.login_id %}
	<br/>
	<br/>
	
	    <form action="/bid/" method="post">
		{% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
	
	    <form action="/sell/" method="post">
		<div style='display:none'><input type='hidden' name='csrfmiddlewaretoken' value='1LCNvgIeObXRQFeOIssbypZK3hFuIilu' /></div>

		<label for="id_quantity">Quantity:</label><input type="number" name="quantity" /><br/>
		<label for="id_price">Price:</label></th><td><input type="number" step="0.05" name="price" /><br/>
		<label for="id_share">Share:</label></th><td><select name="share"><br/>
		{% for share in sellShares %}
<option value="{{share.0}}">{{share.1}}</option>
		{% endfor %}
</select>
        <input type="submit" value="Submit">
    </form>
	
  {% else %}
  <li class="dropdown" id="menu1">
             <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
               Login
                <b class="caret"></b>
             </a>
             <div class="dropdown-menu">
               <form style="margin: 0px" accept-charset="UTF-8" action="/checklogin/" method="post">
				{% csrf_token %}
				<fieldset class='textbox' style="padding:10px">
                   <input type='email' name ="email" style="margin-top: 8px" type="text" placeholder="Email" />
                   <input type='password' name = "password" style="margin-top: 8px" type="password" placeholder="Password" />
                   <input class="btn-primary" name="commit" type="submit" value="submit" />
                 </fieldset>
               </form>
             </div>
           </li>
	{% endif %}

<h2>Market Watch</h2>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>#</th>
            <th>Share Name</th>
            <th>Opening price</th>
			<th>Current Market Price</th>
            <th>Percentage Change</th>
        </tr>
    </thead>
	
    <tbody>	
{% for share in market %}
	<tr>
		<th>{{forloop.counter}}</th>
		<th>{{share.name}}</th>
		<th>{{share.starting_price}}</th>
		<th>{{share.current_price}}</th>
		<th>{{share.percentage}}</th>
	</tr>
{% endfor %}
</table>

<h2>Pending Buy Orders</h2>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>#</th>
            <th>Share Name</th>
			<th>Bid Value</th>
            <th>No. Of Shares</th>
			<th>Modify</th>
        </tr>
    </thead>
	
    <tbody>	
{% for share in pendingBids %}
	<tr>
		<th>{{forloop.counter}}</th>
		<th>{{share.share_name}}</th>
		<th>{{share.price}}</th>
		<th>{{share.quantity}}</th>
		<th>Modify</th>
	</tr>
{% endfor %}
</table>
	
<h2>Pending Sell Orders</h2>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>#</th>
            <th>Share Name</th>
			<th>Offer Value</th>
            <th>No. Of Shares</th>
			<th>Modify</th>
        </tr>
    </thead>
	
    <tbody>	
{% for share in pendingOffers %}
	<tr>
		<th>{{forloop.counter}}</th>
		<th>{{share.share_name}}</th>
		<th>{{share.price}}</th>
		<th>{{share.quantity}}</th>
		<th>Modify</th>
	</tr>
{% endfor %}
</table>	
	
<h2>Current Holdings</h2>

<table class="table table-striped table-bordered table-condensed">
    <thead>
        <tr>
            <th>#</th>
            <th>Share Name</th>
			<th>Buying Price</th>
			<th>Current Price</th>
            <th>No. Of Shares</th>
			<th>Profit/Loss</th>
        </tr>
    </thead>
	
    <tbody>	
{% for share in currentHoldings %}
	<tr>
		<th>{{forloop.counter}}</th>
		<th>{{share.share_name}}</th>
		<th>{{share.buying_price}}</th>
		<th>{{share.current_price}}</th>
		<th>{{share.quantity}}</th>
		<th>{{share.profit}}</th>
	</tr>
{% endfor %}
</table>	
	
</body>
</html>